Added YB controller port
yugabyte/charts pull request #170
Opened 2023-06-26 03:46 UTC by shinji62

Added YBC Port.
Port will not be added if YBC enabled is false.

2023-06-30 01:15 UTC, shinji62 commented
@bhavin192 Hope you can check that as well, my prospect may need the YBC to be exposed as well.

2023-06-30 10:01 UTC, bhavin192 requested changes
Thank you for working on this. I have added few suggestions, once those are addressed, we can merge this.

2023-06-30 10:01 UTC, bhavin192 commented on stable/yugabyte/templates/multicluster/service-per-pod.yaml
> +        {{- if (($root.Values.ybc.enabled))}}
You can just use `$` character instead of `$root` like we have done it on the line number 4. So, it will be 
```
$.Values.ybc.enabled
```

2023-06-30 10:01 UTC, bhavin192 commented on stable/yugabyte/templates/multicluster/service-per-pod.yaml
> +      {{- end}}
```suggestion
    {{- if (eq $label "grpc-ybc-port") }}
    {{- if $.Values.ybc.enabled }}
    - name: {{ $label | quote }}
      port: {{ $port }}
    {{- end }}
    {{- else }}
    - name: {{ $label | quote }}
      port: {{ $port }}
    {{- end }}
```

How about keeping the indentation of template conditions same as YAML block, it is easy to add new YAML blocks that way.

2023-06-30 10:01 UTC, bhavin192 commented on stable/yugabyte/templates/service.yaml
> +      {{- end}}
```suggestion
    {{- if (eq $label "grpc-ybc-port") }}
    {{- if $root.Values.ybc.enabled }}
    - name: {{ $label | quote }}
      port: {{ $port }}
    {{- end }}
    {{- else }}
    - name: {{ $label | quote }}
      port: {{ $port }}
    {{- end }}
```

2023-06-30 10:01 UTC, bhavin192 commented on stable/yugabyte/templates/multicluster/service-per-pod.yaml
> +{{- $root := . -}}
```suggestion
```

2023-06-30 10:01 UTC, bhavin192 commented on stable/yugabyte/templates/service.yaml
> +            name: "grpc-ybc-port"
```suggestion
        {{- with index $service.ports "grpc-ybc-port" }}
        ports:
          - containerPort: {{ . }}
            name: "grpc-ybc-port"
        {{- end }}
```

We should use `with` here, as some of the users might have modified the `Services:` section. This section is an array which means these users will have whole section copied and added to the provider overrides. If we don't use with, their deployments will break. They won't have this new grpc-ybc-port field in their overrides.

This port is already exposed in case of normal users who use headless services. So, let's try not to break the installation for them.

2023-07-03 01:05 UTC, shinji62 commented on stable/yugabyte/templates/multicluster/service-per-pod.yaml
> +      {{- end}}
I think much difficult to read but fine.

2023-07-03 01:11 UTC, shinji62 commented
@bhavin192 thanks for the review I think everything have been addressed.

2023-07-03 13:03 UTC, bhavin192 approved these changes
Looks good! I tested following scenarios and it is working fine.
- ServicePerPod enabled, YBC enabled: each service has the port mentioned.
- YBC enabled, but `grpc-ybc-port` not in the list: port is not added, and installation is successful. This can happen when someone has overridden the Service section in their YBA configuration.
- YBC disabled: port is not added.

2023-07-03 13:20 UTC, merged