Fix hostname in credentials configmap
yugabyte/charts pull request #184
Opened 2024-01-22 14:16 UTC by zadjadr

The actual services created have the `Release.Name` as a prefix.

2024-01-31 10:31 UTC, bhavin192 requested changes
Thank you for sending the pull request. 

The actual prefix is generated using `yugabyte.fullname` it takes care of truncating longer Helm release names to correct length. I would suggest saving the correct FQDN as a variable and then using it in those commands.

2024-01-31 10:31 UTC, bhavin192 commented on stable/yugabyte/templates/setup-credentials-configmap.yaml
```suggestion
{{- $serviceName := .Values.oldNamingStyle | ternary "yb-tservers" (printf "%s-yb-tservers" (include "yugabyte.fullname" . )) }}
{{- $tserverFQDN := printf "%s.%s.svc.%s" $serviceName .Release.Namespace .Values.domainName }}
```

2024-01-31 10:31 UTC, bhavin192 commented on stable/yugabyte/templates/setup-credentials-configmap.yaml
> +      /home/yugabyte/bin/ysqlsh -h {{ .Release.Name }}-yb-tservers.{{ .Release.Namespace }}.svc.{{ .Values.domainName }}
```suggestion
      /home/yugabyte/bin/ysqlsh -h {{ $tserverFQDN }}
```
We can do the same thing for all the occurrences.

2024-01-31 11:11 UTC, zadjadr commented on stable/yugabyte/templates/setup-credentials-configmap.yaml
> +      /home/yugabyte/bin/ycqlsh {{ .Release.Name }}-yb-tservers.{{ .Release.Namespace }}.svc.{{ .Values.domainName }}
```suggestion
      /home/yugabyte/bin/ycqlsh {{ $tserverFQDN }}
```

2024-01-31 11:12 UTC, zadjadr commented on stable/yugabyte/templates/setup-credentials-configmap.yaml
> +        /home/yugabyte/bin/ysqlsh -h {{ .Release.Name }}-yb-tservers.{{ .Release.Namespace }}.svc.{{ .Values.domainName }}
```suggestion
        /home/yugabyte/bin/ysqlsh -h {{ $tserverFQDN }}
```

2024-02-01 08:44 UTC, bhavin192 commented on stable/yugabyte/templates/setup-credentials-configmap.yaml
> +{{- $tserverFQDN := printf "%s.%s.svc.%s" $serviceName .Release.Namespace .Values.domainName }}
```suggestion

    {{- $serviceName := .Values.oldNamingStyle | ternary "yb-tservers" (printf "%s-yb-tservers" (include "yugabyte.fullname" . )) }}
    {{- $tserverFQDN := printf "%s.%s.svc.%s" $serviceName .Release.Namespace .Values.domainName }}

```

2024-02-01 08:45 UTC, bhavin192 approved these changes

2024-02-01 08:47 UTC, merged