Modified to deploy multiple YB clusters in the single namespace
yugabyte/charts pull request #50
Opened 2020-12-16 18:22 UTC by baba230896

### Summary

- Modified the Helm charts for multiple YB deployments in the single namespace.
- Now Helm Charts have two naming conventions, the old naming convention will be used by default, and to tweak the naming convention for the deployment of multiple YB clusters in the single namespace use `oldNamingStyle: false` or  `--set oldNamingStyle=false`.
- Migration won't possible for the old naming convention to the new naming convention due to `volumeClaimTemplates` because it creates the PVC every time whenever it gets a new combination of `given name + pod name`.

### Test Plan:

The following test scenarios have been tested so far.
**Test Environment:** OpenShift and GKE, `ysqlsh` with Northwind DB, and tested externally through EC2 instance.

1. Created a YB cluster with the old naming convention, upgraded with the `quay.io/yugabyte/yugabyte-itest:2.5.1.0-b90` image, and at last, upgraded with TLS flag. 
2. Created 2 YB clusters with the new naming convention, upgraded with the `quay.io/yugabyte/yugabyte-itest:2.5.1.0-b90` image, and at last, upgraded with TLS flag. 
3. Created a YB cluster with the new naming convention, upgraded with the `quay.io/yugabyte/yugabyte-itest:2.5.1.0-b90` image, and then upgraded with TLS flag but with the wrong path of certs to test rollback. And at last, after rollback, again upgraded with TLS flag.
4. Created a YB cluster using charts hosted on `charts.yugabyte.com`, upgraded with the `quay.io/yugabyte/yugabyte-itest:2.5.1.0-b90` image using these changes (keeping `oldNamingStyle: true`), and at last, upgraded with TLS flag. 
5. Created a YB cluster using charts hosted on `charts.yugabyte.com`, and try to upgrade without any change using these changes (keeping `oldNamingStyle: true`). And as expected, the pods haven't restarted.
6. Created a YB cluster with ServiceMonitor using charts hosted on `charts.yugabyte.com`, upgraded with the `quay.io/yugabyte/yugabyte-itest:2.5.1.0-b90` image using these changes (keeping `oldNamingStyle: true`), and at last, upgraded with TLS flag. 
7. Created a YB cluster with ServiceMonitor (With 53 Characters Release name) using charts hosted on `charts.yugabyte.com`, upgraded with the `quay.io/yugabyte/yugabyte-itest:2.5.1.0-b90` image using these changes (keeping `oldNamingStyle: true`), so the changes will remove the old SM and deploy the new SM using the new naming convention because previously `_helpers.tpl` trimming the 63 characters but now it is 43 characters. And throughout the upgrading process pod won't restart because we aren't upgrading the naming convention for pods.
8. Created a YB cluster with ServiceMonitor (new naming convention), upgraded with the `quay.io/yugabyte/yugabyte-itest:2.5.1.0-b90` image, and at last, upgraded with TLS flag. 

fixes https://github.com/yugabyte/yugabyte-db/issues/6355

2021-01-29 14:01 UTC, bhavin192 commented on stable/yugabyte/templates/service.yaml
> +                  - {{ $root.Release.Name | quote }}
Having the release label here means that two YugabyteDB pods can be on same node if they are part of different releases. _Also some pod with old naming scheme can be with a pod of new naming scheme._

2021-01-30 01:16 UTC, jvigil-yugabyte requested changes
In general, it would be an awesome feature to be able to support multiple YB clusters in a single namespace. This is a great step in that direction. However, it seems like this PR makes some bigger changes than just adding that capability. It modifies the naming convention for a few different objects (for example, `*-tls-client-cert` -> `*-client-tls`). In order to support the naming convention changes, it's my opinion that the extensive use of ternary operators add a lot of complexity to our chart overall and might not be worth it.

It seems like we could add support for running multiple YB clusters in the same namespace in a simpler way by creating an optional "namingPrefix" field in the values.yml file. If specified, the prefix will be prepended to all of the objects that need unique naming. Otherwise, an empty string will be prepended and it will have no effect. What do you think about that plan? Or, maybe I am missing some context on why these larger naming convention changes are necessary.

Also, maybe we want to split the template functions for generating the labels into a separate commit / PR? It's a nice refactor that cleans up our duplicate label generation everywhere and probably deserves to be it's own separate thing :100:

2021-01-30 01:16 UTC, jvigil-yugabyte commented on stable/yugabyte/templates/_helpers.tpl
>  {{- define "yugabyte.name" -}}
Do we use this template anywhere? It looks like we might be able to delete it.

2021-01-30 01:16 UTC, jvigil-yugabyte commented on stable/yugabyte/templates/_helpers.tpl
> +app.kubernetes.io/name: "{{ .label }}"
Is there any reason why we wouldn't want to switch to using the recommended app name label all the time? ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

CC: @Arnav15, @iSignal

2021-02-01 05:53 UTC, iSignal commented
@jvigil-yugabyte : not sure I follow the line of thought. In general, there is already a unique naming prefix available to us - the release name, why would we introduce another? 

As for the complexity of choosing between old and new formats, it arises from the problem of maintaining compatibility with older versions, not from the approach of the PR itself. If we can introduce a breaking major version upgrade at some point, it allows us to get rid of the complexity but until then, we will have to support both formats.

2021-02-01 18:16 UTC, jvigil-yugabyte commented
@iSignal good point, I did not realize we had the release name as a unique prefix. We could definitely use that. My proposal was around simplifying the changes (for this PR / feature) by utilizing a unique prefix, rather than creating an entirely new naming convention.

For example, we could replace the changes like:
```
name: {{ $root.Values.oldNamingStyle | ternary "yugabyte-tls-client-cert" (printf "%s-client-tls" (include "yugabyte.fullname" $root)) }}
```
... with something like:
```
name: {{ (printf "%syugabyte-tls-client-cert" .Values.namingPrefix }}
```

This way, we could retain the old naming convention, yet also add support for unique names (if so desired). Though, if we do want to eventually change our overall naming convention, then I agree, we will have to find some way to make a breaking change / upgrade to the helm chart.

2021-02-05 07:30 UTC, iSignal approved these changes

2021-02-05 07:30 UTC, iSignal commented on stable/yugabyte/templates/service.yaml
> +          - "--rpc_bind_addresses={{ printf "$(HOSTNAME).%s-%s.$(NAMESPACE).svc.%s" (include "yugabyte.fullname" $root) .name $root.Values.domainName }}"
this pattern appears a bunch of times so it would be better to make this a utility function in helpers

2021-02-05 13:47 UTC, jvigil-yugabyte approved these changes

2021-02-05 13:49 UTC, jvigil-yugabyte commented
After chatting w/ @iSignal, it seems we need to support backwards compatibility, so the `oldNamingStyle` flag is necessary.

2021-02-12 19:41 UTC, merged