[yugabyte] Add liveness check based on disk IO
yugabyte/charts pull request #96
Opened 2021-10-21 13:31 UTC by bhavin192

- In some Kubernetes setups it is possible that underlying disk dies and writes from TServer fail but this failure is not detected immediately, instead it is detected only during next write operation by TServer.
- This adds a simple liveness check to the database pods to check if the disk is readable and writable.

If the probe fails 3 times in a row, it will be marked as failed. The probe is checked every 10 seconds, so this will take 30 seconds in total.

### Scenarios tested:

- Installed the chart using latest master.
- Upgraded it with these changes.
- YB-Master and YB-TServer pods run as expected.
- Tried the storage.ephemeral and skipHealthChecks flags as well, the
  liveness probe is not added in case of these flags.

Fixes https://github.com/yugabyte/yugabyte-db/issues/10345

2021-10-22 17:00 UTC, iSignal requested changes

2021-10-22 17:00 UTC, iSignal commented on stable/yugabyte/templates/service.yaml
>                        cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
are you thinking that this serves as a sufficient preflight check? it is reasonable but if so, we should comment explicitly because it is hard to understand for future devs. we could also explicitly `touch` the file anyway just in case this log cleanup code changes later.

2021-10-22 17:00 UTC, iSignal commented on stable/yugabyte/templates/_helpers.tpl
> +    {{- if ne $index 0 }} {{ end }}/mnt/disk{{ $index -}}/disk.check
if we are going to pass these to touch, we should quote them in case they have spaces in them

2021-10-25 07:22 UTC, bhavin192 commented on stable/yugabyte/templates/service.yaml
>                        cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
No, I don't think the postStart is correct place for this check, though it serves as yet another place which is doing disk related operations, and fail in case of issues. 

The container command and this postStart command start asynchronously, so it is possible that our database process starts first and then fails.

Like Jason was saying, we should have a preflight check for this.

2021-10-25 08:05 UTC, bhavin192 commented on stable/yugabyte/templates/service.yaml
>                        cp /home/yugabyte/bin/log_cleanup.sh /mnt/disk0/yb-data/scripts;
I have added a new preflight check for this.

2021-10-26 01:07 UTC, iSignal approved these changes

2021-10-26 01:07 UTC, merged